"""initial schema - companies, managers, clients

Revision ID: 1c31037c9840
Revises: 
Create Date: 2026-04-27 13:03:05.908121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c31037c9840'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('management_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('default_email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('management_companies', schema=None) as batch_op:
        batch_op.create_index('ix_company_name', ['name'], unique=False)
        batch_op.create_index('ix_company_status', ['status'], unique=False)

    op.create_table('property_managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['management_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property_managers', schema=None) as batch_op:
        batch_op.create_index('ix_manager_company', ['company_id'], unique=False)
        batch_op.create_index('ix_manager_email', ['email'], unique=False)
        batch_op.create_index('ix_manager_name', ['name'], unique=False)
        batch_op.create_index('ix_manager_status', ['status'], unique=False)

    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('building_name', sa.String(length=255), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('default_company_id', sa.Integer(), nullable=True),
    sa.Column('default_manager_id', sa.Integer(), nullable=True),
    sa.Column('send_directly_to_client', sa.Boolean(), nullable=False),
    sa.Column('client_email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['default_company_id'], ['management_companies.id'], ),
    sa.ForeignKeyConstraint(['default_manager_id'], ['property_managers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index('ix_client_address', ['address'], unique=False)
        batch_op.create_index('ix_client_building', ['building_name'], unique=False)
        batch_op.create_index('ix_client_company', ['default_company_id'], unique=False)
        batch_op.create_index('ix_client_owner', ['owner_name'], unique=False)
        batch_op.create_index('ix_client_status', ['status'], unique=False)
        batch_op.create_index('ix_client_unit', ['unit'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index('ix_client_unit')
        batch_op.drop_index('ix_client_status')
        batch_op.drop_index('ix_client_owner')
        batch_op.drop_index('ix_client_company')
        batch_op.drop_index('ix_client_building')
        batch_op.drop_index('ix_client_address')

    op.drop_table('clients')
    with op.batch_alter_table('property_managers', schema=None) as batch_op:
        batch_op.drop_index('ix_manager_status')
        batch_op.drop_index('ix_manager_name')
        batch_op.drop_index('ix_manager_email')
        batch_op.drop_index('ix_manager_company')

    op.drop_table('property_managers')
    with op.batch_alter_table('management_companies', schema=None) as batch_op:
        batch_op.drop_index('ix_company_status')
        batch_op.drop_index('ix_company_name')

    op.drop_table('management_companies')
    # ### end Alembic commands ###
